if: branch = master OR tag is present

language: java
jdk:
  - openjdk8

sudo: required
services:
  - docker

# Fix for https://travis-ci.community/t/problematic-docker-compose-version-1-23-1/5362/3
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64 > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - ./gradlew build -x check --scan --no-daemon

jobs:
  include:
    - stage: test
      env: [ NAME=core ]
      script: ./gradlew testcontainers:check javadoc --scan --no-daemon -i

    - stage: test
      env: [ NAME=core ]
      jdk: openjdk11
      script: ./gradlew testcontainers:check --scan --no-daemon -i

    - stage: test
      env: [ NAME=core ]
      jdk: openjdk13
      script: ./gradlew testcontainers:check --scan --no-daemon -i

    - env: [ NAME=selenium ]
      script: ./gradlew selenium:check --scan --no-daemon -i

    - env: [ NAME=modules ]
      script: ./gradlew check -x testcontainers:check -x selenium:check -x jdbc-test:check --scan --no-daemon -i

    - env: [ NAME=jdbc ]
      script: ./gradlew jdbc-test:check --scan --no-daemon -i

    - env: [ NAME=examples ]
      script: cd examples && ../gradlew check --no-daemon -i

    # Run Docker-in-Docker tests inside Alpine
    - env: [ NAME="docker-in-alpine-docker" ]
      script:
        - |
                DOCKER_HOST=unix:///var/run/docker.sock DOCKER_TLS_VERIFY= docker run -t --rm \
                -v "$HOME/.gradle":/root/.gradle/ \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v "$(pwd)":"$(pwd)" \
                -w "$(pwd)" \
                openjdk:8-jdk-alpine \
                ./gradlew --no-daemon testcontainers:test --tests '*GenericContainerRuleTest' --scan -i

    - stage: deploy
      sudo: false
      services: []
      install: skip
      script: skip
      deploy:
        provider: script
        script: ./gradlew -Pversion=$TRAVIS_TAG release --scan --no-daemon -i
        on:
          tags: true
          branch: master
