site_name: Testcontainers
plugins:
    - search
    - codeinclude
    - markdownextradata
theme:
    name: 'material'
    custom_dir: 'docs/theme'
    palette:
        scheme: testcontainers
    font:
      text: Roboto
      code: Roboto Mono
    logo: 'logo.svg'
    favicon: 'favicon.ico'
extra_css:
    - 'css/extra.css'
repo_name: 'testcontainers-java'
repo_url: 'https://github.com/testcontainers/testcontainers-java'
markdown_extensions:
    - admonition
    - codehilite:
          linenums: False
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
nav:
    - Home: index.md
    - Quickstart:
          - quickstart/junit_4_quickstart.md
          - quickstart/junit_5_quickstart.md
          - quickstart/spock_quickstart.md
    - Features:
          - features/creating_container.md
          - features/networking.md
          - features/commands.md
          - features/files.md
          - features/startup_and_waits.md
          - features/container_logs.md
          - features/creating_images.md
          - features/configuration.md
          - features/image_name_substitution.md
          - features/advanced_options.md
    - Modules:
          - Databases:
                - modules/databases/index.md
                - modules/databases/jdbc.md
                - modules/databases/r2dbc.md
                - modules/databases/cassandra.md
                - modules/databases/cockroachdb.md
                - modules/databases/couchbase.md
                - modules/databases/clickhouse.md
                - modules/databases/db2.md
                - modules/databases/dynalite.md
                - modules/databases/influxdb.md
                - modules/databases/mariadb.md
                - modules/databases/mongodb.md
                - modules/databases/mssqlserver.md
                - modules/databases/mysql.md
                - modules/databases/neo4j.md
                - modules/databases/oraclexe.md
                - modules/databases/orientdb.md
                - modules/databases/postgres.md
                - modules/databases/presto.md
                - modules/databases/trino.md
          - modules/azure.md
          - modules/docker_compose.md
          - modules/elasticsearch.md
          - modules/gcloud.md
          - modules/hivemq.md
          - modules/k3s.md
          - modules/kafka.md
          - modules/localstack.md
          - modules/mockserver.md
          - modules/nginx.md
          - modules/pulsar.md
          - modules/rabbitmq.md
          - modules/solr.md
          - modules/toxiproxy.md
          - modules/vault.md
          - modules/webdriver_containers.md
    - Test framework integration:
          - test_framework_integration/junit_4.md
          - test_framework_integration/junit_5.md
          - test_framework_integration/spock.md
          - test_framework_integration/manual_lifecycle_control.md
    - System Requirements:
          - supported_docker_environment/index.md
          - Continuous Integration:
                - supported_docker_environment/continuous_integration/dind_patterns.md
                - supported_docker_environment/continuous_integration/circle_ci.md
                - supported_docker_environment/continuous_integration/drone.md
                - supported_docker_environment/continuous_integration/gitlab_ci.md
                - supported_docker_environment/continuous_integration/bitbucket_pipelines.md
          - supported_docker_environment/windows.md
          - supported_docker_environment/logging_config.md
          - supported_docker_environment/image_registry_rate_limiting.md
    - Getting help: getting_help.md
    - Contributing:
          - contributing.md
          - contributing_docs.md
          - bounty.md
extra:
    latest_version: 1.17.2
