name: CI-Docker-Wormhole

on:
  pull_request: {}
  push: { branches: [ main ] }

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  in-docker_test:
    runs-on: [self-hosted, Linux,  X64, docker, podman, fedora]
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        run: |
          docker run -i --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME:$HOME" \
            -v "$PWD:$PWD" \
            -w "$PWD" \
            -e AUTO_APPLY_GIT_HOOKS=false \
            openjdk:8-jdk-alpine \
            ./gradlew --no-daemon --continue --scan testcontainers:test --tests '*GenericContainerRuleTest'
