name: Update testcontainers version

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    if: github.repository == 'testcontainers/testcontainers-java'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
      - name: Update testcontainers.version property in gradle.properties
        run: |
          sed -i "s/^testcontainers\.version=.*/testcontainers\.version=${GITHUB_REF_NAME}/g" gradle.properties
          git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v3.10.1
        with:
          title: Update testcontainers version to ${{ github.ref_name }}
          body: |
            Update testcontainers version to ${{ github.ref_name }}
          branch: update-tc-version
          delete-branch: true
