name: Update docs version

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    if: github.repository == 'testcontainers/testcontainers-java'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Update latest_version property in mkdocs.yml
        run: |
          sed -i "s/latest_version: .*/latest_version: ${GITHUB_REF##*/}/g" mkdocs.yml
          git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v3.10.1
        with:
          title: Update docs version to ${GITHUB_REF##*/}
          body: |
            Update docs version to ${GITHUB_REF##*/}
            skip-checks: true
          branch: update-docs-version
          delete-branch: true
