name: Update docs version

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    if: github.repository == 'testcontainers/testcontainers-java'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
      - name: Update latest_version property in mkdocs.yml
        run: |
          sed -i "s/latest_version: .*/latest_version: ${GITHUB_REF_NAME}/g" mkdocs.yml
          git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v3.10.1
        with:
          title: Update docs version to ${{ github.ref_name }}
          body: |
            Update docs version to ${{ github.ref_name }}
            skip-checks: true
          branch: update-docs-version
          delete-branch: true
